Abot.SiteSimulator/Models/PageSpecs.cs
namespace Abot.SiteSimulator.Models
{
    public class PageSpecs
    {
        public int Status200Count { get; set; }

        public int Status403Count { get; set; }

        public int Status404Count { get; set; }

        public int Status500Count { get; set; }

        public int Status503Count { get; set; }

        public int Status200StartingIndex { get; set; }

        public int Status403StartingIndex { get; set; }

        public int Status404StartingIndex { get; set; }

        public int Status500StartingIndex { get; set; }

        public int Status503StartingIndex { get; set; }
    }
}

Abot.SiteSimulator/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Abot.SiteSimulator.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Abot.SiteSimulator/Controllers/HttpResponseController.cs
using System;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace Abot.SiteSimulator.Controllers
{
    public class HttpResponseController : Controller
    {
        public ActionResult Index()
        {
            return Status200();
        }

        public ActionResult Status200()
        {
            Thread.Sleep(100);
            ViewBag.Header = "Status 200";
            ViewBag.Description = "This is a status 200 page";
            return View("BlankPage");
        }

        public ActionResult Status403()
        {
            Thread.Sleep(200);
            throw new HttpException(Convert.ToInt32(HttpStatusCode.Forbidden), "");
        }

        public ActionResult Status404()
        {
            Thread.Sleep(300);
            throw new HttpException(Convert.ToInt32(HttpStatusCode.NotFound), "");
        }

        public ActionResult Status500()
        {
            Thread.Sleep(400);
            throw new HttpException(Convert.ToInt32(HttpStatusCode.InternalServerError), "");
        }

        public ActionResult Status503()
        {
            throw new HttpException(Convert.ToInt32(HttpStatusCode.ServiceUnavailable), "");
        }

        public ActionResult Redirect(int redirectHttpStatus, int destinationHttpStatus)
        {
            if(!IsValidRedirectStatus(redirectHttpStatus))
                throw new ArgumentException("redirectHttpStatus is invalid");

            if (!IsValidDestinationStatus(destinationHttpStatus))
                throw new ArgumentException("destinationHttpStatus is invalid");

            return new RedirectResult("/HttpResponse/Status" + destinationHttpStatus, (redirectHttpStatus == 301));
        }

        private bool IsValidRedirectStatus(int status)
        {
            switch (status)
            {
                case 301:
                case 302:
                    return true;
                default:
                    return false;
            }
        }

        private bool IsValidDestinationStatus(int status)
        {
            switch (status)
            {
                case 200:
                case 403:
                case 404:
                case 500:
                case 503:
                    return true;
                default:
                    return false;
            }
        }
    }
}

Abot.SiteSimulator/Controllers/PageGeneratorController.cs
using Abot.SiteSimulator.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Abot.SiteSimulator.Controllers
{
    public class PageGeneratorController : Controller
    {
        static Dictionary<int, int> _generatedPagesCounts = new Dictionary<int, int>();
        static DateTime refreshCountsTime;

        static PageGeneratorController()
        {
            InitializeCounts();
        }

        private static void InitializeCounts()
        {
            _generatedPagesCounts = new Dictionary<int, int>();
            _generatedPagesCounts.Add(200, 0);
            _generatedPagesCounts.Add(403, 0);
            _generatedPagesCounts.Add(404, 0);
            _generatedPagesCounts.Add(500, 0);
            _generatedPagesCounts.Add(503, 0);

            refreshCountsTime = DateTime.Now.AddSeconds(30);
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Generate(PageSpecs pageSpecs)
        {
            if (pageSpecs == null)
                throw new ArgumentNullException("pageSpecs");

            if (pageSpecs.Status200Count < 0)
                throw new ArgumentException("pageSpecs.Status200 cannot be negative");

            if (pageSpecs.Status403Count < 0)
                throw new ArgumentException("pageSpecs.Status403 cannot be negative");

            if (pageSpecs.Status404Count < 0)
                throw new ArgumentException("pageSpecs.Status404 cannot be negative");

            if (pageSpecs.Status500Count < 0)
                throw new ArgumentException("pageSpecs.Status500 cannot be negative");

            if (pageSpecs.Status503Count < 0)
                throw new ArgumentException("pageSpecs.Status503 cannot be negative");

            if (DateTime.Now > refreshCountsTime)
                InitializeCounts();

            PageSpecs finalSpecs = new PageSpecs();

            lock (_generatedPagesCounts)
            {
                finalSpecs.Status200Count = pageSpecs.Status200Count;
                _generatedPagesCounts[200] += pageSpecs.Status200Count;
                finalSpecs.Status200StartingIndex = (_generatedPagesCounts[200] - pageSpecs.Status200Count) + 1;

                finalSpecs.Status403Count = pageSpecs.Status403Count;
                _generatedPagesCounts[403] += pageSpecs.Status403Count;
                finalSpecs.Status403StartingIndex = (_generatedPagesCounts[403] - pageSpecs.Status403Count) + 1;

                finalSpecs.Status404Count = pageSpecs.Status404Count;
                _generatedPagesCounts[404] += pageSpecs.Status404Count;
                finalSpecs.Status404StartingIndex = (_generatedPagesCounts[404] - pageSpecs.Status404Count) + 1;

                finalSpecs.Status500Count = pageSpecs.Status500Count;
                _generatedPagesCounts[500] += pageSpecs.Status500Count;
                finalSpecs.Status500StartingIndex = (_generatedPagesCounts[500] - pageSpecs.Status500Count) + 1;

                finalSpecs.Status503Count = pageSpecs.Status503Count;
                _generatedPagesCounts[503] += pageSpecs.Status503Count;
                finalSpecs.Status503StartingIndex = (_generatedPagesCounts[503] - pageSpecs.Status503Count) + 1;
            }

            return View("GeneratedPage", finalSpecs);
        }

        public ActionResult ClearCounters()
        {
            InitializeCounts();

            return Content("Counts Cleared!");
        }
    }
}

Abot.SiteSimulator/Controllers/ThrottlingController.cs
using System;
using System.Web.Mvc;

namespace Abot.SiteSimulator.Controllers
{
    public class ThrottlingController : Controller
    {
        static DateTime? _lastServedDate = null;

        public ActionResult Index()
        {
            return View("Index");
        }

        public ActionResult Handle1RequestEveryXSeconds(int seconds)
        {
            DateTime lastServedDate = _lastServedDate.HasValue ? _lastServedDate.Value : default(DateTime);
            double milliSinceLastRequest = (DateTime.Now - lastServedDate).TotalMilliseconds;

            if (milliSinceLastRequest > ((seconds * 1000) - 1))
            {
                _lastServedDate = DateTime.Now;
                return new HttpResponseController().Status200();
            }

            return new HttpResponseController().Status503();
        }

        public ActionResult ResetLastServcedDate()
        {
            _lastServedDate = default(DateTime);

            return View("BlankPage");
        }
    }
}

Abot.SiteSimulator/Views/Home/Index.cshtml
@using Abot.SiteSimulator.Models;
@{
    ViewBag.Title = "Index";
}

<h2>Site Simulator</h2>

<!-- 24005 pages expected -->
@*<a href="/PageGenerator/Generate?Status200Count=500&Status403Count=10&Status404Count=20&Status500Count=30&Status503Count=40&Page=1">Page1</a>
<a href="/PageGenerator/Generate?Status200Count=500&Status403Count=10&Status404Count=20&Status500Count=30&Status503Count=40&Page=2">Page2</a>
<a href="/PageGenerator/Generate?Status200Count=500&Status403Count=10&Status404Count=20&Status500Count=30&Status503Count=40&Page=3">Page3</a>
<a href="/PageGenerator/Generate?Status200Count=500&Status403Count=10&Status404Count=20&Status500Count=30&Status503Count=40&Page=4">Page4</a>*@

<!-- 61 pages expected -->
<a href="/PageGenerator/Generate?Status200Count=5&Status403Count=1&Status404Count=2&Status500Count=3&Status503Count=4&Page=1">Page1</a>
<a href="/PageGenerator/Generate?Status200Count=5&Status403Count=1&Status404Count=2&Status500Count=3&Status503Count=4&Page=2">Page2</a>
<a href="/PageGenerator/Generate?Status200Count=5&Status403Count=1&Status404Count=2&Status500Count=3&Status503Count=4&Page=3">Page3</a>
<a href="/PageGenerator/Generate?Status200Count=5&Status403Count=1&Status404Count=2&Status500Count=3&Status503Count=4&Page=4">Page4</a>
<a href="http://yahoo.com/">Yahoo</a>
<a href="http://zoogle.com/">Zoogle</a>

Abot.SiteSimulator/Views/PageGenerator/GeneratedPage.cshtml
@model Abot.SiteSimulator.Models.PageSpecs

@{
    ViewBag.Title = "GeneratedPage";
}

<h2>Generated Page</h2>

@for(int i = 0; i < Model.Status200Count; i++) 
{
  @Html.ActionLink("Click me to see a 200 status", "Status200/Page" + (i + Model.Status200StartingIndex), "HttpResponse", null, null)<br />
}    
@for (int i = 0; i < Model.Status403Count; i++)
{
  @Html.ActionLink("Click me to see a 403 status", "Status403/Page" + (i + Model.Status403StartingIndex), "HttpResponse", null, null)<br />    
}    
@for (int i = 0; i < Model.Status404Count; i++)
{
  @Html.ActionLink("Click me to see a 404 status", "Status404/Page" + (i + Model.Status404StartingIndex), "HttpResponse", null, null)<br />        
}   
@for (int i = 0; i < Model.Status500Count; i++)
{
  @Html.ActionLink("Click me to see a 500 status", "Status500/Page" + (i + Model.Status500StartingIndex), "HttpResponse", null, null)<br />        
}    
@for (int i = 0; i < Model.Status503Count; i++)
{
  @Html.ActionLink("Click me to see a 503 status", "Status503/Page" + (i + Model.Status503StartingIndex), "HttpResponse", null, null)<br />
}  


@{
    var text = "<div><div><div><div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div></div></div></div>";
    for (int i = 0; i < 30; i++)
    {
        @Html.Raw(text);
    }
}

Abot.SiteSimulator/Views/Shared/BlankPage.cshtml
@{
    ViewBag.Title = ViewBag.Header;
}

<h2>@ViewBag.Header</h2>

@ViewBag.Description


@{
    var text = "<div><div><div><div>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div></div></div></div>";
    for (int i = 0; i < 30; i++)
    {
        @Html.Raw(text);
    }
}

Abot.SiteSimulator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
</head>

<body>
    @RenderBody()
</body>
</html>

Abot.SiteSimulator/Views/Throttling/Index.cshtml
@{
    ViewBag.Title = "Throttling";
}

<h2>Throttling Links</h2>
Crawler should find 24 pages (this page + 23 links). All of the links below will return a 200 status on a perfect throttling implementation.<br />
@{int linkCount = 1;}

@for (int i = 0; i < 15; i++ )
{
    if( (i % 3) == 0)
    {
        @Html.ActionLink(linkCount + ": 200 status page", "Status200", "HttpResponse", new { guid = Guid.NewGuid().ToString()}, null)<br />   
    }
    else if ((i % 5) == 0)
    {
        @Html.ActionLink(linkCount + ": If requested before 10 seconds pass in between requests, then will 503", "Handle1RequestEveryXSeconds", new { seconds = 10, guid = Guid.NewGuid().ToString() })<br />
    } 
    else
    {
        @Html.ActionLink(linkCount + ": If requested before 3 seconds pass in between requests, then will 503", "Handle1RequestEveryXSeconds", new { seconds = 3, guid = Guid.NewGuid().ToString() })<br />
        linkCount++;
        @Html.ActionLink(linkCount + ": If requested before 1 second passes in between requests, then will 503", "Handle1RequestEveryXSeconds", new { seconds = 1, guid = Guid.NewGuid().ToString() })<br />
    }
    
    linkCount++;
 } 